/* define your array of object literals here */
var books = [
	new Book("0132145375",
		"Database Processing", 
		"Appropriate for all contemporary undergraduate database management courses. Database Processing reflects a new teaching method that gets students straight to the point with its thorough and modern presentation of all the key database processing fundamentals.",
		["Piedmont College", "Dallas Baptist University", "Saint Cloud State University"]),
	new Book("0133970744",
		"The Basics of Web Design: HTML5 & CSS3",
		"The Basics of Web Design: HTML5 and CSS3, Third Edition takes a unique approach to prepare students to design web pages that work today in addition to being ready to take advantage of HTML5 coding techniques of the future.",
		["University of West Georgia", "Wake Forest University", "Towson University", "Edge Hill University"]),
	new Book("0132991292",
		"The Economic Way of Thinking",
		"The Economic Way of Thinking goes beyond explaining the basic principles of micro- and macroeconomic analysis by showing students a method of reasoning that teaches them how to apply these principles as tools.",
		["Rhode Island College", "Jackson State University", "Eastern Michigan University", "Mount Royl University", "University of Saskatchewan"]),
	new Book("0133485080",
		"Intro to Engineering Analysis",
		"The goal of this text is to introduce a general problem-solving approach for the beginning engineering student.  Thus, Introduction to Engineering Analysis  focuses on how to solve (any) kind of engineering analytical problem in a logical and systematic way.",
		["Hillsdale College", "University of Alabama in Huntsville", "Georgia Southern University", "Edge Hill University"]),
	new Book("013336092X",
		"Starting Out with C++: Early Objects",
		"Tony Gaddis’s accessible, step-by-step presentation helps beginning students understand the important details necessary to become skilled programmers. His approach is gradual and highly accessible, ensuring that students understand the logic behind developing high-quality programs.",
		["Coastal Carolina University", "University of Dayton", "Bowling Green State University"]),
];